### ISSUE TITLE
[Bug] 应用闪退

### ISSUE THREAD

**Issue by zhblmy** [Richasy/Bili.Copilot#251]
### Bug 描述

当打开一个4K视频后，切换另一个4K视频，出现闪退。
[applog.2024-01-21.log](https://github.com/Richasy/Bili.Copilot/files/13998725/applog.2024-01-21.log)

无独显，使用核显UHD 630  原生播放器   硬解

版本	Windows 11 专业版 Insider Preview
版本	22H2
安装日期	‎2024/‎1/‎19
操作系统版本	23619.1000
体验	Windows Feature Experience Pack 1000.23619.1000.0

### 复现问题的步骤

```plain text
1.打开应用
2.点击4K视频播放
3.点击另一个4K视频
4.应用出现闪退
```

### 预期行为

当打开一个4K视频后，切换另一个4K视频，应用正常使用。

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

体验	Windows Feature Experience Pack 1000.23619.1000.0

### 运行设备

桌面/台式机

### 日志记录

2024/01/21 01:34:09.874|Error|Bili.Copilot.Models.App.Other.ServiceException: 请求超时|Status Code: 0
Bili.Copilot.Models.App.Other.ServiceException: 请求超时
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bili.Copilot.Libs.Provider.HttpProvider.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Bili.Copilot.Libs.Provider.HttpProvider.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bili.Copilot.Libs.Provider.HttpProvider.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bili.Copilot.Libs.Provider.SearchProvider.GetSearchSuggestionAsync(String keyword, CancellationToken cancellationToken)
   at Bili.Copilot.ViewModels.SearchBoxViewModel.LoadSearchSuggestionAsync()
2024/01/21 01:42:04.574|Error|An exception occurred while the application was running|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bili.Copilot.Libs.Provider.UpdateProvider.GetGitHubLatestReleaseAsync()
   at Bili.Copilot.ViewModels.AppViewModel.CheckUpdateAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
2024/01/21 01:44:22.359|Error|An exception occurred while the application was running|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bili.Copilot.Libs.Provider.UpdateProvider.GetGitHubLatestReleaseAsync()
   at Bili.Copilot.ViewModels.AppViewModel.CheckUpdateAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
[applog.2024-01-21.log](https://github.com/Richasy/Bili.Copilot/files/13998731/applog.2024-01-21.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by zhblmy** [comment]
更新核显驱动程序后已解决。
