### ISSUE TITLE
[Bug] 尝试连接小幻助理失败AppUnavailable

### ISSUE THREAD

**Issue by 1PercentSync** [Richasy/Bili.Copilot#27]
### Bug 描述

点击视频总结时显示：尝试连接小幻助理失败AppUnavailable

### 复现问题的步骤

```plain text
打开应用
右键一个视频
点击总结
```

### 预期行为

正常总结视频

### 截图

<img width="1720" alt="Desktop Screenshot 2023 08 06 - 20 51 44 27" src="https://github.com/Richasy/Bili.Copilot/assets/127626920/786079a0-6279-416b-894f-102ac2c5ef89">

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2023-08-06.log](https://github.com/Richasy/Bili.Copilot/files/12271047/applog.2023-08-06.log)

### 备注

ai连接方式的应用服务不能正常工作
协议启动是可以的

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
你的小幻助理版本是……另外，你说的 `协议启动可以的`，指的是可以通过协议启动打开小幻助理，然后能正常显示 AI 总结的内容吗？

**Comment by NalCol** [comment]
> 你的小幻助理版本是……另外，你说的 `协议启动可以的`，指的是可以通过协议启动打开小幻助理，然后能正常显示 AI 总结的内容吗？

我这边也是AppUnavailable，协议启动可以输出。
![image](https://github.com/Richasy/Bili.Copilot/assets/58576200/fe87ce9e-2506-4624-8144-06589b87d203)

**Comment by NalCol** [comment]
其中一段Log

```
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2023/08/07 10:15:30.969|Error|An exception occurred while the application was running|System.Exception: 尝试连接小幻助理失败 AppUnavailable
   at Bili.Copilot.ViewModels.AIFeatureViewModel.ConnectToFantasyCopilotServiceAsync()
   at Bili.Copilot.ViewModels.AIFeatureViewModel.InitializeAsync()
   at Bili.Copilot.ViewModels.AIFeatureViewModel.SummarizeVideoAsync(VideoIdentifier video)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
```

**Comment by 1PercentSync** [comment]
> 你的小幻助理版本是……另外，你说的 `协议启动可以的`，指的是可以通过协议启动打开小幻助理，然后能正常显示 AI 总结的内容吗？

小幻助理版本：1.2308.1.0
是的，协议启动按预期运行

**Comment by gyxxgzy** [comment]
+1，协议启动正常生效，应用服务显示AppUnavailable
小幻助理版本1.2308.1.0

**Comment by Richasy** [comment]
请安装 .NET SDK 7 <https://dotnet.microsoft.com/zh-cn/download/dotnet/7.0>，下载安装后可以正常使用
