### ISSUE TITLE
[Bug] 原生播放器解码器选项丢失

### ISSUE THREAD

**Issue by fxzxmicah** [Richasy/Bili.Copilot#340]
### Bug 描述

原生播放器解码器选项丢失。

### 复现问题的步骤

```plain text
打开应用
转到“设置”页
```

### 预期行为

这一选项在更新前的旧版本中是存在的。

### 截图

在原生选项下：
![image](https://github.com/Richasy/Bili.Copilot/assets/48860358/671ac784-a69d-4d71-a94d-c71ffea0d6c8)
在FFmpeg选项下：
![image](https://github.com/Richasy/Bili.Copilot/assets/48860358/f3f2972b-e857-4daf-9cca-9a5ec6082fa4)

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

应用商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22631)

### 运行设备

桌面/平板或笔记本

### 日志记录

2024/03/05 00:17:12.225|Error|System.ArgumentException: 参数错误。
|System.ArgumentException: 参数错误。

   at WinRT.DelegateExtensions.DynamicInvokeAbi(Delegate del, Object[] invoke_params)
   at ABI.Windows.Foundation.Collections.IMapMethods`2.Insert(IObjectReference obj, K key, V value)
   at ABI.System.Collections.Generic.IDictionaryMethods`2.Add(IObjectReference obj, K key, V value)
   at Bili.Copilot.ViewModels.NativePlayerViewModel.GetVideoClient()
   at Bili.Copilot.ViewModels.NativePlayerViewModel.LoadDashVideoSourceAsync(Boolean audioOnly)
   at Bili.Copilot.ViewModels.NativePlayerViewModel.SetSourceAsync(SegmentInformation video, SegmentInformation audio, Boolean audioOnly)
   at Bili.Copilot.ViewModels.PlayerDetailViewModel.SelectVideoFormatAsync(FormatInformation format)

### 备注

在选择FFmpeg的情况下，重新进入设置页也会发生选项丢失的情况：
![image](https://github.com/Richasy/Bili.Copilot/assets/48860358/c45c2846-63ea-444f-b875-253a73d41c10)

### 人人为我，我为人人

我更擅长发现问题

**Comment by btandylau** [comment]
确实，没法选择H264/H265/AV1了
