### ISSUE TITLE
[Bug] 无法唤出任务栏

### ISSUE THREAD

**Issue by pheotry** [Richasy/Bili.Copilot#380]
### Bug 描述

Win11开启了自动隐藏任务栏后，如果全屏了，鼠标移动到底部，任务栏无法呼出。

题外话：使用mpv播放视频的时候感觉流畅很多啊，不过不支持弹幕。

### 复现问题的步骤

```plain text
开启自动隐藏任务栏，
软件最大化窗口。
鼠标移动到底部
```

### 预期行为

任务栏正常呼出

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

2024/04/13 18:46:43.752|Error|An exception occurred while the application was running|System.InvalidOperationException: 此时媒体播放器尚未就绪
   at Bili.Copilot.ViewModels.PlayerDetailViewModel.EnsureMediaPlayerExist()
   at Bili.Copilot.ViewModels.PlayerDetailViewModel.PlayPause()
   at Bili.Copilot.App.Controls.Base.BiliPlayerOverlay.OnInteractionControlTapped(Object sender, TappedRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Input.TappedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个属于系统或框架的问题，我这边没法解决
