### ISSUE TITLE
[Bug] 视频无限缓冲，无法播放

### ISSUE THREAD

**Issue by SA-Root** [Richasy/Bili.Copilot#393]
### Bug 描述

登录后点击任意视频或直播即开始缓冲，无法正常播放，日志显示HTTP 403错误：rate limit exceeded。重新登录账号仍会遇到同样的问题。

### 复现问题的步骤

```plain text
1.打开应用
2.登录账号
3.点击任意视频
```

### 预期行为

正常加载视频并播放

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2

### 运行设备

桌面/平板或笔记本

### 日志记录

2024/05/06 15:01:55.381|Error|An exception occurred while the application was running|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bili.Copilot.Libs.Provider.UpdateProvider.GetGitHubLatestReleaseAsync()
   at Bili.Copilot.ViewModels.AppViewModel.CheckUpdateAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

### 人人为我，我为人人

None

**Comment by HuangDayu** [comment]
我点播放就直接挂掉了

**Comment by Richasy** [comment]
请在设置里切换其它播放器类型，比如 ffmpeg，或者软硬解之类的

**Comment by SA-Root** [comment]
> 请在设置里切换其它播放器类型，比如 ffmpeg，或者软硬解之类的

试了一些组合，在切换到ffmpeg/硬解/H.265时能正常播放视频，但直播无法播放，错误信息如下：
2024/05/15 14:58:54.271|Error|System.Exception: 播放失败: [avformat_open_input] I/O error (-5)|System.Exception: 播放失败: [avformat_open_input] I/O error (-5)

**Comment by Richasy** [comment]
新版本发布后可以试试新的播放器，目前这个bug暂时关闭
