### ISSUE TITLE
[Bug] AI错误

### ISSUE THREAD

**Issue by xiaolan610** [Richasy/Bili.Copilot#621]
### Bug 描述

# Gemini、自定义接口GPT用不了~
截图：
<img width="829" alt="BiliCopilot UI_K4hObCapyD" src="https://github.com/user-attachments/assets/768e0e26-f3f6-4d88-b5cc-7bdaefc30c08">
<img width="750" alt="BiliCopilot UI_1j6tavRDQC" src="https://github.com/user-attachments/assets/6f334df6-1591-46d2-b728-32020f95e3af">
<img width="749" alt="BiliCopilot UI_w6TEabRC7u" src="https://github.com/user-attachments/assets/78a7a48f-b31f-4106-b988-81cffcff497b">

日志：
```Log
2024/09/20 22:09:46.528|Error|OpenAI | gpt-4 发生错误|Microsoft.SemanticKernel.HttpOperationException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:7897)
 ---> Azure.RequestFailedException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:7897)
 ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:7897)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessSyncOrAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessSyncOrAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsStreamingAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)

2024/09/20 22:09:17.757|Error|OpenAI | gpt-4o-mini 发生错误|System.NotSupportedException: Multi-filed events not supported.
   at Azure.Core.Sse.SseReader.TryReadSingleFieldEventAsync()
   at Azure.Core.Sse.SseAsyncEnumerator`1.EnumerateFromSseStream(Stream stream, Func`2 multiElementDeserializer, CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.Sse.SseAsyncEnumerator`1.EnumerateFromSseStream(Stream stream, Func`2 multiElementDeserializer, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
2024/09/20 22:09:19.003|Error|core: libdav1d: Unknown Metadata OBU type 6
|
2024/09/20 22:09:20.950|Error|OpenAI | gpt-4o-mini 发生错误|System.NotSupportedException: Multi-filed events not supported.
   at Azure.Core.Sse.SseReader.TryReadSingleFieldEventAsync()
   at Azure.Core.Sse.SseAsyncEnumerator`1.EnumerateFromSseStream(Stream stream, Func`2 multiElementDeserializer, CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.Sse.SseAsyncEnumerator`1.EnumerateFromSseStream(Stream stream, Func`2 multiElementDeserializer, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
2024/09/20 22:09:24.003|Error|core: libdav1d: Unknown Metadata OBU type 6
|
2024/09/20 22:09:25.197|Error|OpenAI | gpt-4 发生错误|System.NotSupportedException: Multi-filed events not supported.
   at Azure.Core.Sse.SseReader.TryReadSingleFieldEventAsync()
   at Azure.Core.Sse.SseAsyncEnumerator`1.EnumerateFromSseStream(Stream stream, Func`2 multiElementDeserializer, CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.Sse.SseAsyncEnumerator`1.EnumerateFromSseStream(Stream stream, Func`2 multiElementDeserializer, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
2024/09/20 22:09:29.030|Error|core: libdav1d: Unknown Metadata OBU type 6
|
2024/09/20 22:09:30.365|Error|Gemini | gemini-1.5-pro 发生错误|Microsoft.SemanticKernel.HttpOperationException: Response status code does not indicate success: 400 (Bad Request).
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.SemanticKernel.Http.HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Http.HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.Google.Core.ClientBase.SendRequestAndGetResponseImmediatelyAfterHeadersReadAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.Google.Core.GeminiChatCompletionClient.StreamGenerateChatMessageAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.Google.Core.GeminiChatCompletionClient.StreamGenerateChatMessageAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
```

### 复现问题的步骤

```plain text
GPT填了个免费的公益API，就是延迟有点高，
然后测试，报错
Gemini就是原版的。
```

### 预期行为

修复！

### 截图

已截图~

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-20.log](https://github.com/user-attachments/files/17076837/applog.2024-09-20.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
Gemini 原版的话你不需要填写终结点啊，那个是给代理用的。

至于 OpenAI 代理，虽然没有条件复现，但从你的日志来看，是服务端那边返回的数据结构不符合标准 Open AI 的 ChatStream 接口
