### ISSUE TITLE
[Bug] 混元API-签名计算错误

### ISSUE THREAD

**Issue by shiikoe** [Richasy/Bili.Copilot#774]
### Bug 描述

在成功调用混元API生成了两次之后就没有结果了。然后我翻看了应用程序错误日志：

```
2024/10/07 00:12:28.781|Error|HunYuan | hunyuan-lite 发生错误|Microsoft.SemanticKernel.KernelException: **HunYuan API doesn't return any data.**
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.ValidateHunYuanResponse(HunYuanMessageResponse response)
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.ProcessChatResponseStreamAsync(Stream responseStream, CancellationToken ct)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.ProcessChatResponseStreamAsync(Stream responseStream, CancellationToken ct)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.ProcessChatResponseStreamAsync(Stream responseStream, CancellationToken ct)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.GetStreamingChatMessageContentsOrPopulateStateForToolCallingAsync(ChatCompletionState state, Stream responseStream, CancellationToken ct)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.GetStreamingChatMessageContentsOrPopulateStateForToolCallingAsync(ChatCompletionState state, Stream responseStream, CancellationToken ct)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.GetStreamingChatMessageContentsOrPopulateStateForToolCallingAsync(ChatCompletionState state, Stream responseStream, CancellationToken ct)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.StreamGenerateChatMessageAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.StreamGenerateChatMessageAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.HunYuan.Core.HunYuanChatCompletionClient.StreamGenerateChatMessageAsync(ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
   at BiliAgent.Core.AgentClient.SendMessageAsync(ProviderType type, String modelId, String message, Action`1 streamingAction, CancellationToken cancellationToken)
```

以及混元后台的错误提示：
AuthFailure.SignatureFailure 签名错误。签名计算错误，请对照调用方式中的签名方法文档检查签名计算过程。

![image](https://github.com/user-attachments/assets/20e2b651-d6b0-4830-b7d0-c7255dd09373)

我看了账号后台的资源包一切正常，继续点击调用，混元后台的API错误计数会增加。

### 复现问题的步骤

```plain text
点击视频
点击ai生成
一闪而过
```

### 预期行为

应该正常输出内容。

我同时还配置了gemini，谷歌的API还是我自己反代的，实测可用。

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
有时候服务并不稳定，可以多试几次。

不过我看到腾讯混元开放了与 OpenAI 兼容的接口，你可以在这里生成你的 API KEY：https://console.cloud.tencent.com/hunyuan/api-key

然后参考：https://agent.richasy.net/chat-config#%E4%BB%A3%E7%90%86%E4%B8%8E-api-%E5%85%BC%E5%AE%B9

将生成的 API KEY 和代理链接（https://api.hunyuan.cloud.tencent.com/v1）填进设置里，创建一个ID 为 hunyuan-pro 的自定义模型。

这种看上去会更稳定，因为省去了签名计算的步骤：

![image](https://github.com/user-attachments/assets/9b2161ce-99e5-4081-b4d1-c09fbf13e428)
