### ISSUE TITLE
[Bug] 无法加载动态；无法搜索。grpc.biliapi.net 拒绝连接。

### ISSUE THREAD

**Issue by Yukai-Qian** [Richasy/Bili.Copilot#925]
### Bug 描述

动态页面显示 “未找到指定数据” ；搜索页面显示空白。网页版 bilibili 正常。

日志中出现错误，例如：

```log
2024/11/29 23:25:12.216|Error|加载动态列表失败.|Richasy.BiliKernel.KernelException: 未知错误：Call failed. No connection could be made because the target machine actively refused it. (grpc.biliapi.net:443): POST https://grpc.biliapi.net/bilibili.app.dynamic.v2.Dynamic/DynVideo
 ---> Flurl.Http.FlurlHttpException: Call failed. No connection could be made because the target machine actively refused it. (grpc.biliapi.net:443): POST https://grpc.biliapi.net/bilibili.app.dynamic.v2.Dynamic/DynVideo
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (grpc.biliapi.net:443)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Richasy.BiliKernel.Http.BiliHttpClient.SendAsync(IFlurlRequest request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Richasy.BiliKernel.Http.BiliHttpClient.SendAsync(IFlurlRequest request, CancellationToken cancellationToken)
   at Richasy.BiliKernel.Services.Moment.Core.MomentClient.GetVideoMomentsAsync(String offset, String baseline, CancellationToken cancellationToken)
   at BiliCopilot.UI.ViewModels.Components.VideoMomentSectionDetailViewModel.LoadItemsAsync()
```

### 复现问题的步骤

```plain text
1. 打开应用
2. 打开 “动态”，等待加载，显示 “未找到指定的数据” 
3. 搜索任意关键词
4. 显示空白界面
```

### 预期行为

正常打开动态、搜索页面

### 截图

![image](https://github.com/user-attachments/assets/644d5fdf-6765-4616-b924-259143f4bec8)
![image](https://github.com/user-attachments/assets/dfae0be1-d78a-4257-841a-dbe677b32a2e)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-11-29.log](https://github.com/user-attachments/files/17964273/applog.2024-11-29.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
看上去你正在使用网络代理或者类似 Ad guard 之类的广告屏蔽软件，请在对应软件的屏蔽规则中找到 grpc.biliapi.net 相关的条目，删除即可

**Comment by Yukai-Qian** [comment]
谢谢！经检查，是由于 Portmaster 拦截了请求。
