### ISSUE TITLE
[Bug] 哔哩搜索结果页偶现卡死，需要手动结束进程

### ISSUE THREAD

**Issue by Yebingiscn** [Richasy/Bili.Copilot#957]
### Bug 描述

哔哩搜索页面滑动出现卡死，整个窗口消失，需要手动结束进程才能重新使用哔哩

### 复现问题的步骤

```plain text
暂时无法复现
1. 哔哩搜索任意关键词
2. 点击视频“无痕播放”后立即退出
3. 继续向下滑动
出现卡死
```

### 预期行为

确认是否为哔哩bug，如是则修复bug不再出现卡死现象

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

2024/12/26 11:16:03.049|Error|Unhandled exception occurred.|System.NullReferenceException: Object reference not set to an instance of an object.
   at BiliCopilot.UI.ViewModels.Core.IslandPlayerViewModel.OnCloseAsync()
   at BiliCopilot.UI.ViewModels.View.VideoPlayerPageViewModel.CleanAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
2024/12/26 11:16:04.307|Error|Unhandled exception occurred.|System.ArgumentNullException: Value cannot be null. (Parameter 'window')
   at WinUIEx.WindowExtensions.GetWindowHandle(Window window)
   at BiliCopilot.UI.Controls.Core.IslandPlayer.OnControlLoaded()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 人人为我，我为人人

None

**Comment by Ziphyrien** [comment]
确实，不只是搜索页，经常卡住
